ajax_simple_project/ajax_app/urls.py
from django.urls import path
from .views import FirstPage
from .views import ValidationView
# from .views import validate_username

app_name = 'ajax'

urlpatterns = [
    path("", FirstPage.as_view(), name="first_page"),
    path("validate", ValidationView.as_view(), name="validate")
]

ajax_simple_project/ajax_simple_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

app_name = 'ajax'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ajax_app.urls')),
    path('signal', include('signals.urls')),
]

ajax_simple_project/signals/urls.py
from django.urls import path
from .views import SignalView

app_name = 'signal'

urlpatterns = [
    path('', SignalView.as_view(), name='sign'),
]

ajax_simple_project/ajax_app/models.py
from django.db import models


# Create your models here.

class Utilizador(models.Model):

    username = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'UTILIZADOR'
        verbose_name = 'UTILIZADOR'
        verbose_name_plural = 'UTILIZADORES'

    def __str__(self):
        return self.username

ajax_simple_project/signals/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Signals
# There are two key elements in the signals: the senders and the receivers
# The sender is the one responsible to dispatch a signal
# A sender must be either a Python object, or None to receive signals
# The receiver is the one will receive this signal and then do something
# A receiver must be a function or an instance method which is to receive signals

# The connection between the senders and the receivers is done through "signal dispatchers"
# Which are instances of Signal, via the connect method


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        db_table = 'PROFILE'
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return str(self.user)


def create_profile(sender, instance, created, **kwargs):
    # whenever signal calls this method/this receiver we are going to check if this is the first instance
    # (created it's a boolean that it will be True if a new record was created! )
    # if it is we are going ahead and create a new Profile
    # Ver de novo !!!!
    print("entro no create_profile")
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_profile, sender=User)
# this connects the receiver to the sender
# every single time the save method is called it's going to trigger the method on receiver after the save is completed
# and listen to the model on the sender


def update_profile(sender, instance, created, **kwargs):
    print("entro no update_profile")
    if created is False:
        instance.profile.save()
        # this is where it will be logic
        print("Profile updated!")


post_save.connect(update_profile, sender=User)


# @models.permalink
# def get_absolute_url(self):
#     return('item', (), {'pk': self.id, 'slug':self.slug})

# def __unicode(self):
#     return self.title

ajax_simple_project/ajax_app/views.py
import json
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.views.generic import View
from django.http import JsonResponse
from .models import Utilizador


class FirstPage(CreateView):

    template_name = 'signup.html'
    form_class = UserCreationForm


class ValidationView(View):
    http_method_names = ['post']

    def post(self, request):
        print("cheguei aqui!!!!!")
        response = self.validate_username(request)
        response_content_json = json.loads(response.content)

        if response_content_json['is_taken'] is False:
            Utilizador.objects.create(username=response_content_json['username'])

        return response

    def validate_username(self, request):

        username = request.POST.get('username', None)
        data = {
            'is_taken': Utilizador.objects.filter(username__iexact=username).exists()
        }
        if data['is_taken']:
            data['error_message'] = 'User with this username already exist'
        else:
            data['username'] = username
        return JsonResponse(data)

ajax_simple_project/signals/views.py
from django.http import HttpResponse
from django.views.generic import View
# Create your views here.


class SignalView(View):
    def get(self, request):
        return HttpResponse("<h1> sadasd </h1>")

ajax_simple_project/ajax_app/templates/base.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Default Title{% endblock %}</title>
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    <header>
      ...
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
      ...
    </footer>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js "
    crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

ajax_simple_project/ajax_app/templates/signup.html
{% extends 'base.html' %}

{% block javascript %}
     <script>

    // $("#id_username").change(function () {
    //      // var username = $(this).val();
    //      var form = $(this).closest("form")
    //      $.ajax({
    //          url: form.attr("data_validate_username_url"),
    //          data: form.serialize(),
    //          dataType : 'json',

    //         success: function (data){
    //       if(data.is_taken){
    //         alert(data.error_message)
    //       }
    //     }
    //      });


    // });

    $("#btnSubmit").click(function(event){
      event.preventDefault();
      var form = $(this).closest("form")
      // console.log("vou imprimir o form " + form)
      //var username = $(this).val();
        // var username if on top it was $("#id_username").change(function(){})
        // but we want the whole form !
      $.ajax({
          type: "POST",
          url: form.attr("data_validate_url"),
          //data: {'username': username}
          data: form.serialize(),
          csrfmiddlewaretoken: '{{ csrf_token }}',
          dataType: 'json',
          success: function(data){
            if(data.is_taken){
              alert(data.error_message)
            }
            if(data.username){
              $('#output').html("bem vindo " + data.username)

            }
          }
      });
    });



  </script>

{% endblock %}
{% block content %}
  <form method="post" data_validate_url="{% url 'ajax:validate' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="btnSubmit"type="submit">Sign up</button>
  </form>

  <div id="output">

  </div>
{% endblock %}